import "@coinbase/onchainkit/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import ThemeProvider from "./components/ThemeProvider"; // Import ThemeProvider

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME || "Polaris AI",
  description: "Generated by `create-onchain`, a Next.js template for OnchainKit",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-background text-black dark:bg-black dark:text-white">
        <ThemeProvider> {/* Wrapping the whole app with ThemeProvider */}
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
